sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  allow_failures:
    - php: 7.3
    - php: 7.4
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --prefer-source -n
