language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

sudo: false

install:
  - composer self-update

before_script:
  - composer install --prefer-source -n
